services:
  database:
    build:
      context: . 
      dockerfile: Dockerfile.database 
    container_name: global-city-growth-database
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432" 

  orchestrator:
    build:
      context: . 
      dockerfile: Dockerfile.orchestrator 
    container_name: global-city-growth-orchestrator
    ports:
      - "3000:3000" 
    volumes:
      - .:/app 
    depends_on:
      - database 
    command: ["tail", "-f", "/dev/null"] # TODO: remove this and add dagster commands

volumes:
  postgres_data: 
