services:
  database:
    build:
      context: . 
      dockerfile: Dockerfile.database 
    container_name: global-city-growth-database
    env_file:
      - path: ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5451:5432" 

  orchestrator:
    build:
      context: . 
      dockerfile: Dockerfile.orchestrator 
    container_name: global-city-growth-orchestrator
    env_file:
      - path: ./.env
    ports:
      - "3000:3000" 
    volumes:
      - .:/app 
    depends_on:
      - database 
    command: ["tail", "-f", "/dev/null"] # TODO: remove this and add dagster commands

volumes:
  postgres_data: 
