sources:
  - name: ghsl
    schema: public
    tables:
      - name: world_raster_ghsl_pop_all_years
      - name: world_raster_ghsl_smod_all_years

  - name: cshapes
    schema: public
    tables:
      - name: world_country_borders_raw
      - name: world_crosswalk_cshapes_code_to_iso_code

  - name: owid
    schema: public
    tables:
      - name: world_urbanization_raw
      - name: countries_with_regions