sources:
  - name: convolved_raster
    schema: public
    tables:
      - name: usa_raster_census_place_convolved_all_years
  
  - name: matching
    schema: public
    tables:
      - name: usa_crosswalk_component_id_to_cluster_id