models:
  - name: world_population_share_cities_above_1m_historical
    description: "The urban (note urban not total!) population share of cities above 1 million. This is computed from the population data by summing the total population and that of cities above 1 million."
    columns:
      - name: country
        description: "see world_cluster_growth_geocoding"
      - name: year
      - name: analysis_id
        description: "see world_cluster_growth_population_country_analysis"
      - name: urban_population_share_cities_above_one_million
        description: "The urban population share of cities above 1 million"

  - name: world_population_share_cities_above_1m_projections
    description: "The urban population share of cities above 1 million projected into the future. The projections are based on a simple equation relating the shares to the rank-size slopes: s = (x_max^{1-alpha} - z^{1-alpha}) / (x_max^{1-alpha} - x_min^{1-alpha}) where x_max, x_min are upper and lower bounds of the urban population, z is 1 million, and alpha is the zipf exponent (1 / rank_size_slope). To compute these projections we set x_min = 5000, z = 1 million, and alpha = 1 / rank_size_slope. We set x_max = omega * urban_population, where omega is a free parameter. We tune omega in the marcro get_optimal_omegas_population_share_cities_above_1m_projections."
    columns:
      - name: country
        description: "see world_cluster_growth_geocoding"
      - name: year
      - name: analysis_id
        description: "see world_cluster_growth_population_country_analysis"
      - name: urban_population_share_cities_above_one_million
        description: "The urban population share of cities above 1 million projected with the above method."

  - name: world_population_share_cities_above_1m
    description: "The union of the historical and projected data. Historical data is before 2025 (2025 included), and projections are after 2025 (2025 excluded)."
    columns:
      - name: country
        description: "see world_cluster_growth_geocoding"
      - name: year
      - name: analysis_id
        description: "see world_cluster_growth_population_country_analysis"
      - name: urban_population_share_cities_above_one_million
        description: "The urban population share of cities above 1 million"
      - name: urban_population
        description: "see world_urban_population"
      - name: urban_population_share_group
        description: "see world_urbanization_groups"