models:
  - name: usa_crosswalk_hist_census_place_to_nhgis_census_place
    description: "Crosswalk between historical census places and NHGIS census places. Each historical census place is linked to its closest NHGIS census place."
    columns:
      - name: hist_census_place_id
        description: "see crosswalk_hist_id_to_hist_census_place_raw"
      - name: nhgis_census_place_id
        description: "see usa_nhgis_census_place_geom"
      - name: distance
        description: "The distance between the historical census place and the NHGIS census place"

  - name: usa_nhgis_census_place_migration
    description: "Migration flows between NHGIS census places aggregated from hist census place migration"
    columns:
      - name: census_place_origin
        description: "see usa_nhgis_census_place_migration"
      - name: census_place_destination
        description: "see usa_nhgis_census_place_migration"
      - name: year_origin
      - name: year_destination
      - name: all_migrants
        description: "The number of migrants"

  - name: usa_nhgis_census_place_population
    description: "Population of NHGIS census places aggregated from hist census place population"
    columns:
      - name: census_place_id
        description: "see usa_nhgis_census_place_geom"
      - name: year
      - name: population

  - name: usa_nhgis_census_place_appearances
    description: "Number of times a census place appears in the data and the last year it appears in the data"
    columns:
      - name: census_place_id
        description: "see usa_nhgis_census_place_geom"
      - name: num_appearances
        description: "The number of times the census place appears in the data"
      - name: last_appearance
        description: "The last year the census place appears in the data"

  - name: usa_nhgis_census_place_linked_population
    description: "Linked population of NHGIS census places aggregated from hist census place migration. It is important to note that census place population and linked population are different because not all individuals are linked. To compute migration probabilities, we need to use the linked population, because migrants are part of the linked population."
    columns:
      - name: census_place_id
        description: "see usa_nhgis_census_place_geom"
      - name: year
      - name: population
        description: "The linked population of the census place. Sum of all migrants that were there in the origin year."

  - name: usa_nhgis_census_place_migration_probability
    description: "Migration probability between two census places. It is the ratio of the number of migrants to the linked population of the origin census place."
    columns:
      - name: census_place_origin
        description: "The NHGISPLACE code of the census place where the person was living in the origin year"
      - name: census_place_destination
        description: "The NHGISPLACE code of the census place where the person was living in the destination year"
      - name: year_origin
      - name: year_destination
      - name: migration_probability

  - name: usa_nhgis_census_place_nearest_neighbors
    description: "Nearest neighbors for each NHGIS census place. We use the nearest neighbors as a fallback for places that disappear from the data and for which we have no migration information."
    columns:
      - name: census_place_id
        description: "see usa_nhgis_census_place_geom"
      - name: neighbor_census_place_id
        description: "The NHGISPLACE code of the nearest neighbor"
      - name: distance
        description: "The distance between the census place and the nearest neighbor"

  - name: usa_nhgis_census_place_equivalence_network
    description: "Equivalence network between NHGIS census places. The edges of this network are decided based on the following rules: 1. If a census place disappears from the data, we select a 'continuation' place and link it to the census place that disappeared. This continuation place is: (a) the census place that has the highest migration probability to the disappearing place in the year of disappearance; (b) the census place that is the nearest neighbor of the disappearing place. 2. If two census places have a high migration probability, we link them. The migration probability is considered high if it is higher than 0.t and the distance between the places is less than 30000 meters. 3. We link census place to themselves (because a place is always equivalent to itself)."
    columns:
      - name: left_census_place_id
        description: "The NHGISPLACE code of one endpoint of the edge"
      - name: right_census_place_id
        description: "The NHGISPLACE code of the other endpoint of the edge"

  - name: usa_crosswalk_nhgis_census_place_to_census_place_stable
    description: "Crosswalk from NHGIS census place to census place stable. The ID of the census place stable is the NHGIS ID of the most populous census place in the connected component of the equivalence network. This makes the crosswalk deterministit. "
    columns:
      - name: census_place_stable_id
        description: "The NHGISPLACE code of the stable census place (connected component of the equivalence network)"
      - name: census_place_id
        description: "see usa_nhgis_census_place_geom"

  - name: usa_census_place_stable_population_with_anomaly_flags
    description: "Population of census place stable with anomaly flags. The anomaly flags are set to 1 if the population is anomalous. Anomalous population is defined as a population that grows fast in one year and shrinks fast in the next year, creating a spike or a dip."
    columns:
      - name: census_place_stable_id
        description: "see usa_crosswalk_nhgis_census_place_to_census_place_stable and usa_nhgis_census_place_geom"
      - name: year
      - name: population
      - name: anomaly_flag
        description: "1 if the population is anomalous, 0 otherwise"

  - name: usa_census_place_stable_population_interpolated
    description: "Population of census place stable interpolated where is missing or anomalous. The population is interpolated using the closest population observations."
    columns:
      - name: census_place_stable_id
        description: "see usa_crosswalk_nhgis_census_place_to_census_place_stable and usa_nhgis_census_place_geom"
      - name: year
      - name: population
        description: "The population with interpolated values"
      - name: population_interpolated
        description: "A flag indicating if the population is interpolated or not. 1 if the population is interpolated, 0 otherwise"
        
        
        