models:
  - name: world_population
    description: "The population of the world with future projections until 2100 from Our World in Data"
    columns:
      - name: country
        description: "The world bank code of the country"
      - name: year
      - name: population
        description: "The population of the country"
      - name: projection
        description: "Whether the population is a projection or not"

  - name: world_country_borders
    description: "see world_country_borders_raw"
    columns:
      - name: cntry_name
      - name: gwcode
      - name: gwsyear
      - name: gwsmonth
      - name: gwsday
      - name: gweyear
      - name: gwemonth
      - name: gweday
      - name: geometry
        description: "The geometry of the country borders is set to EPSG:4326. In the original table it is EPSG:4326 but its not set."

  - name: world_urbanization
    description: "see world_urbanization_raw"
    columns:
      - name: country
      - name: year
      - name: urban_population_share